import { getUserBranding, getDefaultBranding, applyBrandingToHTML } from '@/lib/branding-utils';

describe('Branding Utils', () => {
  test('getDefaultBranding returns correct defaults', () => {
    const defaults = getDefaultBranding();
    
    expect(defaults).toEqual({
      logo_url: null,
      primary_color: '#4F46E5',
      accent_color: '#06B6D4',
      footer_text: null
    });
  });

  test('applyBrandingToHTML applies custom colors for Pro users', () => {
    const html = '<div style="color: #4F46E5;">Test</div>';
    const branding = {
      logo_url: null,
      primary_color: '#FF0000',
      accent_color: '#00FF00',
      footer_text: 'Custom Footer'
    };
    
    const result = applyBrandingToHTML(html, branding, true);
    
    expect(result).toContain('#FF0000');
    expect(result).not.toContain('#4F46E5');
  });

  test('applyBrandingToHTML adds watermark for free users', () => {
    const html = '<body><div>Content</div></body>';
    const branding = getDefaultBranding();
    
    const result = applyBrandingToHTML(html, branding, false);
    
    expect(result).toContain('watermark');
    expect(result).toContain('Generated by TweetToCourse');
  });

  test('applyBrandingToHTML removes watermarks for Pro users', () => {
    const html = '<body><div class="watermark">Watermark</div><div>Content</div></body>';
    const branding = getDefaultBranding();
    
    const result = applyBrandingToHTML(html, branding, true);
    
    expect(result).not.toContain('watermark');
  });
});